#hydra-user-serviceBAM
spring:
  application:
    name: hydra-user-service
  datasource:
    url: jdbc:h2:file:~/test
    username: roll
    password: tide
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
  
server:
  port: 8993

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
#eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://18.219.59.193:8761/eureka}

